import type { FAQ } from '@/lib/blog/faqGenerator';

interface AutoGeneratedFAQProps {
    faqs: FAQ[];
    onFormOpen?: () => void;
}

/**
 * Auto-Generated FAQ Komponente
 * - Alle FAQs standardmäßig ausgeklappt (kein Accordion mehr)
 * - FAQPage Schema.org Markup
 * - SEO-optimierte Fragen & Antworten
 * - CTA öffnet Modal
 */
export function AutoGeneratedFAQ({ faqs, onFormOpen }: AutoGeneratedFAQProps) {

    if (!faqs || faqs.length === 0) return null;

    // Schema.org Markup für FAQPage
    const faqSchema = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": faqs.map(faq => ({
            "@type": "Question",
            "name": faq.question,
            "acceptedAnswer": {
                "@type": "Answer",
                "text": faq.answer
            }
        }))
    };

    return (
        <section className="my-16" itemScope itemType="https://schema.org/FAQPage">
            {/* Schema.org Markup */}
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
            />

            {/* Header */}
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-8">
                Häufig gestellte Fragen
            </h2>

            {/* FAQ Liste (alle ausgeklappt) */}
            <div className="space-y-4">
                {faqs.map((faq, index) => (
                    <div
                        key={index}
                        className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm"
                        itemScope
                        itemProp="mainEntity"
                        itemType="https://schema.org/Question"
                    >
                        {/* Question */}
                        <h3
                            className="text-lg font-bold text-gray-900 mb-3"
                            itemProp="name"
                        >
                            {faq.question}
                        </h3>

                        {/* Answer (immer sichtbar) */}
                        <div
                            itemScope
                            itemProp="acceptedAnswer"
                            itemType="https://schema.org/Answer"
                        >
                            <p
                                className="text-gray-700 leading-relaxed"
                                itemProp="text"
                            >
                                {faq.answer}
                            </p>
                        </div>
                    </div>
                ))}
            </div>

            {/* CTA unterhalb FAQs */}
            <div className="mt-8 p-6 bg-gray-50 border border-gray-200 rounded-xl text-center">
                <p className="text-gray-600 mb-4">
                    Haben Sie weitere Fragen? Wir helfen Ihnen gerne weiter!
                </p>
                <button
                    onClick={onFormOpen}
                    className="inline-block px-8 py-3 bg-red-600 text-white rounded-none font-bold hover:bg-red-700 transition-all shadow-md hover:shadow-lg hover:-translate-y-0.5 duration-300"
                >
                    Jetzt kostenlos beraten lassen
                </button>
            </div>
        </section>
    );
}
