"use client";

import { useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { ArrowLeft, Linkedin, CheckCircle2 } from "lucide-react";
import Container from '@/components/Container';
import { Breadcrumbs } from '@/components/Breadcrumbs';
import { KeyTakeaways } from '@/components/blog/content/KeyTakeaways';
import { ConclusionCTA } from '@/components/blog/content/ConclusionCTA';
import { AutoGeneratedFAQ } from '@/components/blog/content/AutoGeneratedFAQ';
import { SocialShareButtons } from '@/components/blog/content/SocialShareButtons';
import { SidebarLeadCTA } from '@/components/blog/sidebar/SidebarLeadCTA';
import { SidebarTOC } from '@/components/blog/sidebar/SidebarTOC';
import { SidebarMiniAbout } from '@/components/blog/sidebar/SidebarMiniAbout';
import { SidebarAbout } from '@/components/blog/sidebar/SidebarAbout';
import { SidebarRelatedArticles } from '@/components/blog/sidebar/SidebarRelatedArticles';
import ContactForm from '@/components/ContactForm';
import type { BlogPost } from '@/lib/blog/posts';

interface BlogPostClientProps {
    post: BlogPost;
    relatedPosts: Array<{ slug: string; title: string }>;
    headings: Array<{ id: string; text: string; level: number }>;
    compiledContent: React.ReactElement;
    readingTime: number;
    slug: string;
}

/**
 * Blog Post Client Component
 * Handles UI rendering and modal state for blog posts
 */
export function BlogPostClient({
    post,
    relatedPosts,
    headings,
    compiledContent,
    readingTime,
    slug
}: BlogPostClientProps) {
    // Modal state
    const [isFormOpen, setIsFormOpen] = useState(false);

    const handleFormOpen = () => {
        setIsFormOpen(true);
    };

    // Conclusion CTA summary
    const conclusionSummary = post.excerpt || "Eine professionelle Website ist die perfekte Basis für Ihr Unternehmen. Bei Red Rabbit Media erhalten Sie nicht nur Design, sondern auch Performance, SEO und langfristige Betreuung.";

    return (
        <div className="min-h-screen bg-[#fafafa] pt-20">
            {/* Contact Form Modal */}
            <ContactForm isOpen={isFormOpen} onClose={() => setIsFormOpen(false)} />

            <main className="py-12 md:py-20 text-left">
                <Container>
                    {/* Header Section (Full Width) */}
                    <header className="max-w-4xl mx-auto mb-12">
                        {/* Breadcrumbs */}
                        <Breadcrumbs items={[
                            { name: 'Home', url: '/' },
                            { name: 'Tipps', url: '/tipps' },
                            { name: post.title, url: `/tipps/${slug}` }
                        ]} />

                        {/* Back Link */}
                        <Link href="/tipps" className="inline-flex items-center gap-2 text-sm text-gray-500 hover:text-[#dc2626] mb-12 transition-colors font-medium">
                            <ArrowLeft size={16} /> Zurück zur Übersicht
                        </Link>

                        {/* Category + Date */}
                        <div className="flex items-center gap-3 mb-6">
                            <span className="text-[#dc2626] text-xs font-bold uppercase tracking-widest bg-red-50 px-3 py-1 rounded-full">
                                {post.category}
                            </span>
                            <span className="text-gray-400 text-sm">
                                {new Date(post.publishedAt).toLocaleDateString('de-AT', { day: '2-digit', month: 'long', year: 'numeric' })}
                            </span>
                        </div>

                        {/* Title */}
                        <h1 className="text-4xl md:text-6xl font-bold text-[#141414] leading-tight mb-10 tracking-tight">
                            {post.title}
                        </h1>

                        {/* Author Card & E-E-A-T Signals */}
                        <div className="flex flex-wrap items-center justify-between gap-6 py-6 border-y border-gray-100 mb-12">
                            <div className="flex items-center gap-4">
                                <div className="w-12 h-12 rounded-full bg-gray-100 flex items-center justify-center font-bold text-gray-600 border border-gray-200">
                                    {post.author.includes("Dmitry") ? "DP" : "TU"}
                                </div>
                                <div>
                                    <div className="flex items-center gap-2">
                                        <span className="font-bold text-[#141414]">{post.author}</span>
                                        <a
                                            href={post.author.includes("Dmitry")
                                                ? "https://www.linkedin.com/in/dmitrypashlov/"
                                                : "https://www.linkedin.com/in/thomasuhlir/"}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className="text-[#0077b5] hover:scale-110 transition-transform"
                                        >
                                            <Linkedin size={18} />
                                        </a>
                                    </div>
                                    <p className="text-xs text-gray-500 uppercase tracking-widest font-medium">
                                        {post.author.includes("Dmitry") ? "Lead Developer" : "CEO Red Rabbit Media | Web-Stratege"}
                                    </p>
                                </div>
                            </div>
                            <div className="flex items-center gap-6">
                                <div className="flex flex-col items-end">
                                    <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1">Status</span>
                                    <div className="flex items-center gap-1.5 text-green-600 font-bold text-xs uppercase tracking-wide">
                                        <CheckCircle2 size={14} /> Fachlich geprüft
                                    </div>
                                </div>
                                <div className="flex flex-col items-end">
                                    <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mb-1">Lesezeit</span>
                                    <div className="text-[#141414] font-bold text-xs uppercase tracking-wide">{readingTime} Min.</div>
                                </div>
                            </div>
                        </div>

                        {/* Featured Snippet Block (Position 0 Optimization) */}
                        {(post.featuredSnippet && post.featuredSnippetTitle) && (
                            <div className="bg-blue-50 border-l-4 border-blue-600 p-6 md:p-8 rounded-r-xl mb-12 shadow-sm">
                                <h2 className="text-2xl font-bold text-[#141414] mb-4">
                                    {post.featuredSnippetTitle}
                                </h2>
                                <p className="text-xl text-gray-800 leading-relaxed font-medium">
                                    {post.featuredSnippet}
                                </p>
                            </div>
                        )}
                    </header>

                    {/* Two-Column Grid (Desktop) / Single Column (Mobile) */}
                    <div className="grid grid-cols-1 lg:grid-cols-[1fr_360px] gap-12">

                        {/* Main Content Column */}
                        <article className="min-w-0">
                            {/* Featured Image (Hero) - Jetzt als erstes visuelles Element */}
                            <div className="relative aspect-video w-full mb-12 rounded-2xl overflow-hidden shadow-soft border border-gray-100">
                                <Image src={post.featuredImage} alt={post.title} fill className="object-cover" priority />
                            </div>

                            {/* Key Takeaways */}
                            {post.keyTakeaways && post.keyTakeaways.length > 0 && (
                                <KeyTakeaways items={post.keyTakeaways} />
                            )}

                            {/* Main Content (MDX) */}
                            <div className="prose prose-lg max-w-none prose-headings:text-[#141414] prose-headings:font-bold prose-p:text-gray-600 prose-p:leading-relaxed prose-strong:text-[#141414] prose-a:text-[#dc2626] prose-a:no-underline hover:prose-a:underline">
                                {compiledContent}
                            </div>

                            {/* Conclusion CTA */}
                            <ConclusionCTA
                                summary={conclusionSummary}
                                stats={post.conclusionStats}
                                onFormOpen={handleFormOpen}
                            />

                            {/* Auto-Generated FAQs */}
                            {post.faqs && post.faqs.length > 0 && (
                                <AutoGeneratedFAQ faqs={post.faqs} onFormOpen={handleFormOpen} />
                            )}

                            {/* Author Bio Section */}
                            {post.author.includes("Dmitry") ? (
                                <div className="mt-20 p-8 md:p-12 bg-white border border-gray-100 rounded-2xl shadow-soft">
                                    <div className="flex flex-col md:flex-row gap-8 items-center md:items-start text-center md:text-left">
                                        <div className="w-24 h-24 rounded-2xl bg-blue-50 flex-shrink-0 flex items-center justify-center font-bold text-4xl text-blue-600 border border-blue-100 shadow-sm">
                                            DP
                                        </div>
                                        <div>
                                            <h4 className="text-2xl font-bold text-[#141414] mb-4">Experten-Profil: Dmitry Pashlov</h4>
                                            <p className="text-gray-600 leading-relaxed mb-6">
                                                Dmitry Pashlov ist der technische Kopf hinter Red Rabbit Media. Als Lead Developer spezialisiert er sich auf Next.js, High-Performance-Architekturen und technische SEO.
                                                Sein Credo: "Code is Poetry – aber nur, wenn er lädt." Er sorgt dafür, dass Ihre Website nicht nur gut aussieht, sondern auch technisch bei Google gewinnt.
                                            </p>
                                            <div className="flex flex-wrap justify-center md:justify-start gap-4">
                                                <button
                                                    onClick={handleFormOpen}
                                                    className="btn-primary py-2 text-sm uppercase tracking-widest font-bold px-6"
                                                >
                                                    Technik-Check anfragen
                                                </button>
                                                <a href="https://www.linkedin.com/in/dmitrypashlov/" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 text-[#141414] font-bold text-sm uppercase tracking-widest hover:text-[#dc2626] transition-colors">
                                                    LinkedIn Profil <span>→</span>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            ) : (
                                <div className="mt-20 p-8 md:p-12 bg-white border border-gray-100 rounded-2xl shadow-soft">
                                    <div className="flex flex-col md:flex-row gap-8 items-center md:items-start text-center md:text-left">
                                        <div className="w-24 h-24 rounded-2xl bg-gray-50 flex-shrink-0 flex items-center justify-center font-bold text-4xl text-[#dc2626] border border-gray-100 shadow-sm">
                                            TU
                                        </div>
                                        <div>
                                            <h4 className="text-2xl font-bold text-[#141414] mb-4">Experten-Profil: Thomas Uhlir MBA</h4>
                                            <p className="text-gray-600 leading-relaxed mb-6">
                                                Als Gründer von Red Rabbit Media kombiniert Thomas Uhlir betriebswirtschaftliche Exzellenz mit technologischer Innovation.
                                                Sein Fokus liegt auf der Entwicklung von Performance-Websites, die durch Schnelligkeit, E-E-A-T Konformität und erstklassiges Design überzeugen.
                                            </p>
                                            <div className="flex flex-wrap justify-center md:justify-start gap-4">
                                                <button
                                                    onClick={handleFormOpen}
                                                    className="btn-primary py-2 text-sm uppercase tracking-widest font-bold px-6"
                                                >
                                                    Beratung anfragen
                                                </button>
                                                <a href="https://www.linkedin.com/in/thomasuhlir/" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 text-[#141414] font-bold text-sm uppercase tracking-widest hover:text-[#dc2626] transition-colors">
                                                    LinkedIn Profil <span>→</span>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            )}

                            {/* Social Share Buttons (replaces Related Posts) */}
                            <SocialShareButtons
                                url={`https://web.redrabbit.media/tipps/${slug}`}
                                title={post.title}
                            />
                        </article>

                        {/* Sidebar (Desktop Only) - NEUE REIHENFOLGE */}
                        <aside className="hidden lg:block space-y-6">
                            {/* NICHT sticky Sections */}
                            <SidebarMiniAbout onFormOpen={handleFormOpen} />
                            <SidebarTOC headings={headings} />
                            <SidebarRelatedArticles articles={relatedPosts} />
                            <SidebarAbout />

                            {/* Als letztes und STICKY: Website-Analyse Box */}
                            <div className="sticky top-24">
                                <SidebarLeadCTA onFormOpen={handleFormOpen} />
                            </div>
                        </aside>
                    </div>

                    {/* Mobile: Sidebar Content Below Article */}
                    <div className="lg:hidden mt-12 space-y-6">
                        <SidebarLeadCTA onFormOpen={handleFormOpen} />
                        <SidebarMiniAbout onFormOpen={handleFormOpen} />
                        <SidebarTOC headings={headings} />
                        <SidebarRelatedArticles articles={relatedPosts} />
                        <SidebarAbout />
                    </div>
                </Container>
            </main>
        </div>
    );
}
